'use strict';
const API=(window.VedantamAPIConfig?.baseUrl||'http://localhost:5000/api/v1').replace(/\/$/,'');
const resources={dashboard:{label:'Dashboard Home'},admissions:{label:'Admissions',endpoint:'/admissions',kind:'admission'},teachers:{label:'Teachers',endpoint:'/teachers',kind:'teacher'},gallery:{label:'Gallery',endpoint:'/gallery',kind:'gallery'},events:{label:'Events',endpoint:'/events',kind:'event'},notices:{label:'Notices',endpoint:'/notices',kind:'notice'},testimonials:{label:'Testimonials',endpoint:'/testimonials',kind:'testimonial'},slides:{label:'Hero Slider',endpoint:'/hero-slides',kind:'slide'},contacts:{label:'Contact Messages',endpoint:'/contacts',kind:'contact'},newsletter:{label:'Newsletter',endpoint:'/newsletter',kind:'newsletter'},settings:{label:'Settings'},profile:{label:'Admin Profile'},password:{label:'Change Password'}};
let token=localStorage.getItem('vedantam_admin_token')||'';let current='dashboard';let cache={};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opt={}){const isForm=opt.body instanceof FormData;const res=await fetch(API+path,{...opt,headers:{...(isForm?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...(opt.headers||{})},credentials:'include'});const json=await res.json().catch(()=>({success:false,message:'Unexpected API response'}));if(!res.ok||json.success===false)throw new Error(json.message||'Request failed');return json;}
function nav(){const n=$('#adminNav');n.innerHTML=Object.entries(resources).map(([k,v])=>`<button class="nav-btn ${k===current?'active':''}" data-key="${k}">${v.label}</button>`).join('');n.onclick=e=>{const b=e.target.closest('button');if(b)show(b.dataset.key)};}
function boot(ok){$('#loginView').classList.toggle('hidden',ok);$('#adminView').classList.toggle('hidden',!ok);if(ok){nav();show(location.hash?.slice(1)||'dashboard');}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));const r=await api('/auth/login',{method:'POST',body:JSON.stringify(data)});token=r.data.token;localStorage.setItem('vedantam_admin_token',token);boot(true)}catch(err){$('#loginMessage').textContent=err.message;$('#loginMessage').className='message error'}};
$('#logoutBtn').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('vedantam_admin_token');token='';boot(false)};$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
async function show(key){current=key;location.hash=key;nav();$('.sidebar').classList.remove('open');$('#pageTitle').textContent=resources[key].label;$('#content').innerHTML='<div class="panel">Loading...</div>';try{if(key==='dashboard')return dashboard();if(key==='settings')return settings();if(key==='profile')return profile();if(key==='password')return password();return list(key)}catch(e){$('#content').innerHTML=`<div class="message error">${esc(e.message)}</div>`}}
async function dashboard(){const {data}=await api('/dashboard/stats');$('#profileBox').textContent='Admin';$('#content').innerHTML=`<div class="stats">${[['Admissions',data.admissions],['Pending',data.pendingAdmissions],['Messages',data.unreadMessages],['Subscribers',data.subscribers],['Teachers',data.teachers],['Gallery',data.gallery],['Events',data.events],['Notices',data.notices]].map(x=>`<article class="stat"><span>${x[0]}</span><br><strong>${x[1]||0}</strong></article>`).join('')}</div><div class="grid two" style="margin-top:18px"><div class="panel"><h2>Recent Admissions</h2>${mini(data.recentAdmissions,'studentName','status')}</div><div class="panel"><h2>Recent Messages</h2>${mini(data.recentContacts,'name','status')}</div></div>`}
function mini(items,title,status){return `<table><tbody>${(items||[]).map(i=>`<tr><td>${esc(i[title])}</td><td><span class="badge">${esc(i[status])}</span></td><td>${new Date(i.createdAt).toLocaleDateString()}</td></tr>`).join('')||'<tr><td>No data yet</td></tr>'}</tbody></table>`}
const fields={teacher:['name','qualification','experience','description','displayOrder','isActive'],gallery:['title','category','description','displayOrder','isFeatured','image'],event:['title','description','eventDate','location','isFeatured','isPublished','image'],notice:['title','body','priority','publishDate','expiresAt','isPublished'],testimonial:['parentName','studentName','message','rating','displayOrder','isPublished','image'],slide:['title','subtitle','badge','ctaText','ctaLink','displayOrder','isActive','image']};
async function list(key){const r=resources[key];const q=new URLSearchParams({limit:100,sort:'-createdAt'});const search=cache[key]?.search||'';if(search)q.set('search',search);const {data}=await api(`${r.endpoint}?${q}`);cache[key]={...(cache[key]||{}),items:data};const canCreate=!!fields[r.kind];$('#content').innerHTML=`<div class="toolbar"><input placeholder="Search ${r.label}" value="${esc(search)}" id="searchBox"><button class="primary" id="searchBtn">Search</button>${canCreate?'<button class="primary" id="newBtn">Add New</button>':''}<button class="primary" id="exportBtn">Export CSV</button></div><div id="formHost"></div><div class="table-wrap">${table(key,data)}</div>`;$('#searchBtn').onclick=()=>{cache[key].search=$('#searchBox').value;list(key)};$('#exportBtn').onclick=()=>csv(key,data);if(canCreate)$('#newBtn').onclick=()=>form(key);}
function table(key,items){return `<table><thead><tr><th>Preview</th><th>Details</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>${items.map(i=>row(key,i)).join('')||'<tr><td colspan="5">No records found.</td></tr>'}</tbody></table>`}
function row(key,i){const k=resources[key].kind;const title=i.title||i.name||i.studentName||i.parentName||i.email;const img=i.imageUrl||i.photoUrl;return `<tr><td>${img?`<img class="thumb" src="${esc(img)}" alt="${esc(title)}">`:''}</td><td><strong>${esc(title)}</strong><br><small>${esc(i.category||i.qualification||i.phone||i.studentName||i.subject||'')}</small><br>${esc(i.description||i.message||i.body||'').slice(0,110)}</td><td><span class="badge">${esc(i.status||i.priority||(i.isPublished===false||i.isActive===false?'Hidden':'Active'))}</span></td><td>${new Date(i.createdAt).toLocaleDateString()}</td><td class="actions">${k==='admission'?`<button class="small ok" onclick="statusAdmission('${i._id}','Approved')">Approve</button><button class="small" onclick="statusAdmission('${i._id}','Rejected')">Reject</button>`:''}${k==='contact'?`<button class="small ok" onclick="markRead('${i._id}')">Mark Read</button>`:''}${fields[k]?`<button class="small" onclick="form('${key}','${i._id}')">Edit</button>`:''}<button class="small danger" onclick="del('${key}','${i._id}')">Delete</button></td></tr>`}
window.statusAdmission=async(id,status)=>{await api(`/admissions/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});list('admissions')};window.markRead=async id=>{await api(`/contacts/${id}`,{method:'PATCH',body:JSON.stringify({status:'Read'})});list('contacts')};window.del=async(key,id)=>{if(confirm('Delete this record?')){await api(`${resources[key].endpoint}/${id}`,{method:'DELETE'});list(key)}};
window.form=(key,id)=>{const r=resources[key], item=(cache[key]?.items||[]).find(x=>x._id===id)||{}, fs=fields[r.kind];$('#formHost').innerHTML=`<form class="panel form-grid" id="editForm"><h2 class="wide">${id?'Edit':'Add'} ${r.label}</h2>${fs.map(f=>input(f,item[f])).join('')}<button class="primary wide">Save</button><div id="saveMsg" class="wide"></div></form>`;$('#editForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);for(const [k,v] of [...fd.entries()]){if(v===''|| (v instanceof File && !v.name))fd.delete(k)}try{await api(`${r.endpoint}${id?'/'+id:''}`,{method:id?'PATCH':'POST',body:fd});$('#saveMsg').className='message success wide';$('#saveMsg').textContent='Saved successfully';list(key)}catch(err){$('#saveMsg').className='message error wide';$('#saveMsg').textContent=err.message}};};
function input(f,v){if(f==='image')return `<label class="wide">Image<input type="file" name="image" accept="image/*"></label>`;if(['description','message','body','subtitle'].includes(f))return `<label class="wide">${f}<textarea name="${f}">${esc(v||'')}</textarea></label>`;if(f.startsWith('is'))return `<label>${f}<select name="${f}"><option value="true" ${v!==false?'selected':''}>Yes</option><option value="false" ${v===false?'selected':''}>No</option></select></label>`;const type=f.toLowerCase().includes('date')?'date':(f==='rating'||f==='displayOrder'?'number':'text');const val=type==='date'&&v?new Date(v).toISOString().slice(0,10):(v??'');return `<label>${f}<input name="${f}" type="${type}" value="${esc(val)}"></label>`}
function csv(key,items){const text=[Object.keys(items[0]||{}).join(','),...items.map(o=>Object.values(o).map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`${key}.csv`;a.click();}
function settings(){$('#content').innerHTML='<div class="panel"><h2>Production Settings</h2><p>Manage API base URL through <code>js/api-config.js</code> or the <code>vedantam-api-base</code> meta tag on deployment. Use Cloudinary free tier for production images.</p></div>'}
async function profile(){const {data}=await api('/auth/me');const a=data.admin;$('#profileBox').textContent=a.name;$('#content').innerHTML=`<form class="panel form-grid" id="profileForm"><label>Name<input name="name" value="${esc(a.name)}"></label><label>Email<input name="email" type="email" value="${esc(a.email)}"></label><button class="primary wide">Save Profile</button><div id="saveMsg" class="wide"></div></form>`;$('#profileForm').onsubmit=async e=>{e.preventDefault();await api('/auth/profile',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#saveMsg').textContent='Profile updated';$('#saveMsg').className='message success wide'}}
function password(){$('#content').innerHTML=`<form class="panel form-grid" id="passForm"><label>Current Password<input name="currentPassword" type="password" required></label><label>New Password<input name="newPassword" type="password" minlength="8" required></label><button class="primary wide">Change Password</button><div id="saveMsg" class="wide"></div></form>`;$('#passForm').onsubmit=async e=>{e.preventDefault();try{await api('/auth/change-password',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#saveMsg').textContent='Password changed';$('#saveMsg').className='message success wide';e.target.reset()}catch(err){$('#saveMsg').textContent=err.message;$('#saveMsg').className='message error wide'}}}
if(token) api('/auth/me').then(()=>boot(true)).catch(()=>boot(false)); else boot(false);
