'use strict';
const API_CONFIG=window.VedantamAPIConfig||{baseUrl:'/api/v1',endpoints:{gallery:'/gallery'}};
const API_BASE=API_CONFIG.baseUrl.replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'}):'';
const month=d=>new Date(d||Date.now()).toLocaleDateString('en-IN',{month:'long',year:'numeric'});
const imgOf=a=>a.coverImage||a.imageUrl||a.galleryImages?.[0]?.url||'logo.png';
async function api(path){const r=await fetch(`${API_BASE}${path}`);const j=await r.json();if(!r.ok||j.success===false)throw new Error(j.message||'Request failed');return j.data||[]}
function card(a){const count=a.photoCount||a.galleryImages?.length||(a.imageUrl?1:0);return `<article class="activity-card" data-cat="${esc(a.category)}" data-title="${esc(a.title).toLowerCase()}"><a href="gallery.html?activity=${encodeURIComponent(a.slug||a._id)}" aria-label="View ${esc(a.title)} gallery"><img src="${esc(imgOf(a))}" alt="${esc(a.title)}" loading="lazy" decoding="async"><div class="activity-body"><span class="activity-date">${fmt(a.eventDate||a.createdAt)}</span><h3>${esc(a.title)}</h3><p>${esc(a.description||'Beautiful moments from Vedantam Play School.')}</p><div class="activity-meta"><b>${count} Photos</b><span>View Gallery →</span></div></div></a></article>`}
async function initListing(){const grid=document.getElementById('activityGrid');if(!grid)return;let data=await api('/gallery?limit=100&sort=-eventDate,-createdAt');let cat='All', q='';const render=()=>{const filtered=data.filter(a=>(cat==='All'||a.category===cat)&&(!q||String(a.title).toLowerCase().includes(q)));grid.innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty-state">No activities found.</div>';const groups={};filtered.forEach(a=>{const m=month(a.eventDate||a.createdAt);(groups[m]??=[]).push(a)});document.getElementById('galleryTimeline').innerHTML=Object.entries(groups).map(([m,items])=>`<div><h3>${esc(m)}</h3><ul>${items.map(i=>`<li>${esc(i.title)}</li>`).join('')}</ul></div>`).join('')};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{cat=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('gallerySearch')?.addEventListener('input',e=>{q=e.target.value.trim().toLowerCase();render()});render()}
let lightboxIndex=0, lightboxImages=[];
function openLightbox(i){lightboxIndex=i;const lb=document.getElementById('lightbox');lb.classList.add('open');lb.setAttribute('aria-hidden','false');paintLightbox()}
function paintLightbox(){const img=document.getElementById('lightboxImg');img.src=lightboxImages[lightboxIndex]?.url||lightboxImages[lightboxIndex]||'';img.style.transform='scale(1)'}
function move(n){lightboxIndex=(lightboxIndex+n+lightboxImages.length)%lightboxImages.length;paintLightbox()}
async function initDetail(){const host=document.getElementById('activityDetail');if(!host)return;const key=new URLSearchParams(location.search).get('activity');if(!key)return;document.querySelector('.gallery-tools')?.remove();document.querySelector('.activity-layout')?.remove();const a=await api(`/gallery/${encodeURIComponent(key)}`);document.title=`${a.title} Gallery | Vedantam Play School`;document.querySelector('meta[name="description"]')?.setAttribute('content',a.description||`Photos from ${a.title} at Vedantam Play School.`);lightboxImages=(a.galleryImages?.length?a.galleryImages:[{url:imgOf(a)}]).sort((x,y)=>(x.displayOrder||0)-(y.displayOrder||0));host.innerHTML=`<section class="activity-hero" style="background-image:linear-gradient(90deg,rgba(10,84,58,.82),rgba(255,139,45,.45)),url('${esc(imgOf(a))}')"><div><a href="gallery.html" class="back-link">← All Activities</a><span>${esc(a.category)}</span><h1>${esc(a.title)}</h1><time>${fmt(a.eventDate||a.createdAt)}</time><p>${esc(a.description||'')}</p></div></section><div class="activity-photo-grid">${lightboxImages.map((im,i)=>`<button class="photo-tile" data-i="${i}"><img src="${esc(im.url)}" alt="${esc(a.title)} photo ${i+1}" loading="lazy" decoding="async"></button>`).join('')}</div>`;host.querySelectorAll('.photo-tile').forEach(b=>b.onclick=()=>openLightbox(+b.dataset.i))}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]'))document.getElementById('lightbox').classList.remove('open');if(e.target.matches('[data-prev]'))move(-1);if(e.target.matches('[data-next]'))move(1);if(e.target.matches('[data-zoom]')){const im=document.getElementById('lightboxImg');im.style.transform=im.style.transform==='scale(1.7)'?'scale(1)':'scale(1.7)'}});
document.addEventListener('keydown',e=>{if(!document.getElementById('lightbox')?.classList.contains('open'))return;if(e.key==='Escape')document.getElementById('lightbox').classList.remove('open');if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
let sx=0;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});document.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>50&&document.getElementById('lightbox')?.classList.contains('open'))move(dx>0?-1:1)},{passive:true});
initListing().catch(()=>{});initDetail().catch(()=>{});
