'use strict';
const navbar=document.getElementById('navbar');const backToTop=document.getElementById('backToTop');const hamburger=document.getElementById('hamburger');const navLinks=document.getElementById('navLinks');
function onScroll(){navbar?.classList.toggle('scrolled',scrollY>20);backToTop?.classList.toggle('visible',scrollY>420);let current='';document.querySelectorAll('main section[id]').forEach(s=>{if(scrollY>=s.offsetTop-130)current=s.id});document.querySelectorAll('.nav-links a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))}addEventListener('scroll',onScroll,{passive:true});onScroll();
hamburger?.addEventListener('click',()=>{const open=hamburger.classList.toggle('open');navLinks.classList.toggle('open',open);hamburger.setAttribute('aria-expanded',String(open))});navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{hamburger?.classList.remove('open');navLinks.classList.remove('open');hamburger?.setAttribute('aria-expanded','false')}));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(!id||id==='#')return;const t=document.querySelector(id);if(t){e.preventDefault();scrollTo({top:t.getBoundingClientRect().top+scrollY-82,behavior:'smooth'})}}));
const reveal=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting){en.target.classList.add('revealed');reveal.unobserve(en.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
document.addEventListener('mousemove',e=>{const card=document.querySelector('.parallax-card');if(!card||innerWidth<900)return;const r=card.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/r.width;const y=(e.clientY-r.top-r.height/2)/r.height;card.style.transform=`rotateY(${x*8}deg) rotateX(${-y*8}deg) translateY(-8px)`});document.querySelector('.parallax-card')?.addEventListener('mouseleave',e=>e.currentTarget.style.transform='');
const form=document.getElementById('admissionForm');const success=document.getElementById('formSuccess');form?.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('[required]').forEach(f=>{const ok=f.checkValidity()&&f.value.trim();f.classList.toggle('field-error',!ok);if(!ok)valid=false});if(!valid){form.animate([{transform:'translateX(0)'},{transform:'translateX(-8px)'},{transform:'translateX(8px)'},{transform:'translateX(0)'}],{duration:360});return}success.hidden=false;success.scrollIntoView({behavior:'smooth',block:'center'});form.reset()});form?.querySelectorAll('input,select,textarea').forEach(f=>f.addEventListener('input',()=>f.classList.remove('field-error')));
document.querySelectorAll('.btn,.learn,.contact-pills a').forEach(btn=>btn.addEventListener('click',e=>{const rip=document.createElement('span');const r=btn.getBoundingClientRect();const s=Math.max(r.width,r.height);rip.style.cssText=`position:absolute;width:${s}px;height:${s}px;left:${e.clientX-r.left-s/2}px;top:${e.clientY-r.top-s/2}px;border-radius:50%;background:rgba(255,255,255,.35);transform:scale(0);animation:ripple .6s linear;pointer-events:none`;btn.appendChild(rip);rip.onanimationend=()=>rip.remove()}));const st=document.createElement('style');st.textContent='@keyframes ripple{to{transform:scale(3);opacity:0}}';document.head.appendChild(st);backToTop?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
